name: destinasi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Folder utama tempat semua gambar disimpan
    - assets/images/

    # Gambar individual (opsional, untuk kejelasan)
    - assets/images/destinasi.jpg
    - assets/images/air1.jpg
    - assets/images/nagano.jpg
    - assets/images/santorini.jpg
    - assets/images/bali.jpg
    - assets/images/swiss.jpg
    - assets/images/capa.jpeg
    - assets/images/kyoto.jpg
